### ISSUE TITLE
Platform becomes unusable when logged in and browser is closed

### ISSUE THREAD

**Issue by bwulff** [slidewiki/slidewiki-platform#1177] opened 2019-06-26 15:04 UTC
When a user is logged into Slidewiki and closes the browser without logging out of Slidewiki before, the next time SlideWiki is used, the editor and other features are not working anymore.

This can be resolved by completely resetting the browser. 

Reported for Chrome 75 on Windows.

**Comment by bwulff** [comment] 2019-06-27 14:23
Promised to create this ticket and since you wanted it I assign it to you @aoelen :P

**Comment by aoelen** [comment] 2019-06-27 15:31
Hehe sure no problem!

**Comment by bwulff** [comment] 2019-07-03 09:50
Tried to reproduce in FF 67.0 on Ubuntu 16.04. **Not successful, works as expected.**

**Comment by bwulff** [comment] 2019-07-03 15:03
The described behavior was observed with the following configurations:
- Windows 7:
  - FrontMotion Firefox 52.0.0.0
  - IE 11
  - Chrome 75.0.3770.100
- Windows 10
  - Firefox 52.0 (32-Bit)
  - IE 11
  - Chrome 75.0.3770.100
  - Edge 42.17134.1.0 (Microsoft Edge HTML 17.17134)

... that seems pretty consistent!

**Comment by aoelen** [comment] 2020-05-07 15:11
Closing the issue since we weren't able to reproduce it

**Closed by aoelen** 2020-05-07 15:11 UTC
Labels: bug, iOCW
