### ISSUE TITLE
Text Spacing (WCAG 1.4.12a)

### ISSUE THREAD

**Issue by VivienDZB** [slidewiki/slidewiki-platform#1231] opened 2020-02-11 10:37 UTC
**Request:** This criterion focuses on the ability to increase spacing between lines, words, letters, and paragraphs. Any combination of these may assist a user with effectively reading text. As well, ensuring users can override author settings for spacing also significantly increases the likelihood other style preferences can be set by the user. For example, a user may need to change to a wider font family than the author has set in order to effectively read text. It does not dictate that authors must set all their content to the specified metrics. Rather, it specifies that an author's content has the ability to be set to those metrics without loss of content or functionality.

**Issue:**
1. https://slidewiki.org/presentation/81127-1/overview-of-accessibility/811271/437649-3/?language=en-/slide-719796-3 
- When the text spacing is increased, information is cut off at the bottom of the page and is therefore lost.

![grafik](https://user-images.githubusercontent.com/48785136/74229103-fe798f80-4cc1-11ea-92d8-55bcc9a135ef.png)

**Hint:**
2. https://slidewiki.org/deck/127411/_/slide/836159-2/836159-2:1/edit
- When changing the text spacing, the "Reset Zoom" icon is pulled apart.

![grafik](https://user-images.githubusercontent.com/48785136/74229215-400a3a80-4cc2-11ea-92ab-e483ca2cd008.png)

**Solution:**
If authors do not set the CSS `height` property, it can help ensure paragraphs expand. Paragraphs need to allow text to increase vertically for languages or scripts which are read horizontally or to increase horizontally for languages or scripts which are read vertically.

**Comment by aoelen** [comment] 2020-07-06 14:10
I was able to reproduce and fix the second issue. However, the first problem is harder to fix, because the content is rendered by RevealJS. It tries to fit the content on the screen by vertical aligning the items, however if there is too much content it won't fit anymore

**Comment by VivienDZB** [comment] 2020-10-14 10:47
Still an issue:
Presentation view - https://slidewiki.org/presentation/81127-1/overview-of-accessibility/811271/437649-3/?language=en-/slide-719796-3

When the text spacing is increased, information is cut off at the bottom of the page and is therefore lost.

**Comment by aoelen** [comment] 2020-11-13 14:30
Unfortunately I have to close this issue. Although it is indeed an issue, fixing is technically very difficult. Firstly, the rendering happens in a dependency (RevealJS), so we would have to clone the code to make changes. But still changing this is very challenging because of how to position of text happens. It is not possible to change this without affecting the rendering of all other slides

**Closed by aoelen** 2020-11-13 14:30 UTC
Labels: iOCW
